# .github/labels.yml

# Critical Production Labels
- name: "critical"
  color: "ff0000"
  description: "🔥 Critical production issue requiring urgent attention"
- name: "automated"
  color: "0052cc"
  description: "Automated pull request"
- name: "release"
  color: "00ff00"
  description: "Release related changes"