# wrangler.toml
name = "piyuo-next"
main = ".open-next/worker.js"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]
compatibility_date = "2025-04-23"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true
