# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/piyuo/piyuo-next/discussions
    about: Please ask and answer questions here.