name: ❓ Question
description: Ask a question or request support
title: "[Question]: "
labels: ["type: question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We're here to help. Please provide as much context as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please ensure you've completed these steps before asking
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation
          required: true
        - label: I have tried to solve this myself
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - How-to/Usage question
        - Configuration help
        - Best practices
        - Troubleshooting
        - Integration question
        - Performance question
        - General question
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know? Please describe your question clearly.
      placeholder: Please describe your question clearly...
    validations:
      required: true

  - type: textarea
    id: context_and_tried
    attributes:
      label: Context & What You've Tried (Optional)
      description: What are you trying to accomplish, and what steps have you already taken to solve this?
      placeholder: |
        I'm trying to...
        I tried:
        1. ...
        2. ...
    # Removed required: true, making this field optional

  - type: input
    id: version
    attributes:
      label: Version (Optional)
      description: What version are you using?
      placeholder: e.g., v1.2.0
    # Removed required: true, making this field optional

  - type: dropdown
    id: environment
    attributes:
      label: Environment (Optional)
      description: What environment are you working in?
      options:
        - Development
        - Testing/Staging
        - Production
        - Local setup
        - Other
    # Removed required: true, making this field optional

  - type: textarea
    id: code
    attributes:
      label: Relevant Code/Configuration (Optional)
      description: Please share any relevant code or configuration.
      render: shell
      placeholder: Paste your code here...
    # Removed required: true, making this field optional

  - type: textarea
    id: additional
    attributes:
      label: Additional Information (Optional)
      description: Any other details, screenshots, or error messages that might be helpful?
      placeholder: Screenshots, error messages, logs, etc...
    # Removed required: true, making this field optional